/*
 * RTaskResult.cs
 *
 * Copyright (C) 2010-2015 by Microsoft Corporation
 *
 * This program is licensed to you under the terms of Version 2.0 of the
 * Apache License. This program is distributed WITHOUT
 * ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
 * Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0) for more details.
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DeployR;

namespace DeployRBroker
{
    /// <summary>
    /// Represents a handle to the result generated by an RTask.
    /// </summary>
    /// <remarks></remarks>
    public interface RTaskResult
    {
        /// <summary>
        /// Maps to a project execution or job identifier
        /// </summary>
        /// <returns>RTask identifier</returns>
        /// <remarks></remarks>
        String getID();

        /// <summary>
        /// RTask type
        /// </summary>
        /// <returns>RTask type</returns>
        /// <remarks></remarks>
        int getType();

        /// <summary>
        /// Task R session generated console output
        /// </summary>
        /// <returns>Task R session generated console output</returns>
        /// <remarks></remarks>
        String getGeneratedConsole();

        /// <summary>
        /// Task R session graphics device generated plots.
        /// </summary>
        /// <returns>Task R session graphics device generated plots.</returns>
        /// <remarks></remarks>
        List<String> getGeneratedPlots();

        /// <summary>
        /// Task R session working directory generated files
        /// </summary>
        /// <returns>Task R session working directory generated files</returns>
        /// <remarks></remarks>
        List<String> getGeneratedFiles();

        /// <summary>
        /// Task R session workspace generated objects
        /// </summary>
        /// <returns>Task R session workspace generated objects</returns>
        /// <remarks></remarks>
        List<RData> getGeneratedObjects();

        /// <summary>
        /// Task generated files stored to DeployR repository
        /// </summary>
        /// <returns>Task generated files stored to DeployR repository</returns>
        /// <remarks></remarks>
        List<String> getStoredFiles();

        /// <summary>
        /// Task success indicator
        /// </summary>
        /// <returns>Task success indicator</returns>
        /// <remarks></remarks>
        Boolean isSuccess();

        /// <summary>
        /// Task interrupted indicator
        /// </summary>
        /// <returns>Task interrupted indicator</returns>
        /// <remarks></remarks>
        Boolean isInterrupted();

        /// <summary>
        /// Task failure indicator
        /// </summary>
        /// <returns>Task failure indicator</returns>
        /// <remarks></remarks>
        Exception getFailure();

        /// <summary>
        /// Task time spent executing R code on server
        /// </summary>
        /// <returns>Task time spent executing R code on server</returns>
        /// <remarks></remarks>
        long getTimeOnCode();

        /// <summary>
        /// Task time spent being processed on server
        /// </summary>
        /// <returns>Task time spent being processed on server</returns>
        /// <remarks></remarks>
        long getTimeOnServer();

        /// <summary>
        /// Task time spent on call to server
        /// </summary>
        /// <returns>Task time spent on call to server</returns>
        /// <remarks></remarks>
        long getTimeOnCall();
    }
}
